# This is a basic workflow to help you get started with Actions

name: Deploy HTML Page on Surge

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: 10

      # Install Surge
      - name: Install Surge
        run: npm install --global surge
      # Rename the index.html file to 200.html
      - name: Rename the index.html file to 200.html
        run: sudo cp ./index.html ./200.html && sudo rm ./index.html
      # Deploy Surge
      - name: Deploy Page to Surge
        run: surge ./ https://explorechat-gtd.surge.sh --token ${{ secrets.SURGE_TOKEN }}
